### ISSUE TITLE
タブを中クリックするとナビゲーションページが新しいウィンドウで表示される

### ISSUE THREAD

**Issue by akurakuu** [mncrp/monot#10]
![image](https://user-images.githubusercontent.com/77902040/175538584-eeafdc0c-a5f7-481a-9d56-70a2772a46fd.png)

**Comment by Sorakime** [comment]
僕の環境でも確認できました
これの原因は、タブのやつが
```html
<span><a href="#">タブ名</a><a href="#"></a></span>
```
となっていて、要は#を中クリックしてウィンドウ開いて表示させてるからですね。修正してみます

**Comment by Sorakime** [comment]
ちょっと前に修正したのでIssueをcloseさせていただきます
