### ISSUE TITLE
English Support

### ISSUE THREAD

**Issue by ItsukaHiro** [mncrp/monot#11]
As the Title, I really want Monot support English.

**Comment by Sorakime** [comment]
Hello, I'm one of Monot developers, Sorakime.
I thank you for this issue. This request is nice. We're planning of the next version v.2.0.0, so we'll implement this feature.

**Comment by ItsukaHiro** [comment]
> Hello, I'm one of Monot developers, Sorakime.
> I thank you for this issue. This request is nice. We're planning of the next version v.2.0.0, so we'll implement this feature.

I'm really looking forward.

**Comment by Sorakime** [comment]
> > Hello, I'm one of Monot developers, Sorakime.
> > I thank you for this issue. This request is nice. We're planning of the next version v.2.0.0, so we'll implement this feature.
> 
> I'm really looking forward.

Thank you.

**Comment by Sorakime** [comment]
![スクリーンショット 2023-03-18 0 08 34](https://user-images.githubusercontent.com/69241694/225944122-cde89808-c8c2-43df-9ce8-8a4cbf037ac4.png)
I implemented it!
What do you think?

**Comment by ItsukaHiro** [comment]
Man, that's pretty good !

**Comment by Sorakime** [comment]
Thanks!
I'm going to make that public and release v.2.0.0 Beta 1!
Please wait for a little...

**Comment by Sorakime** [comment]
We released v.2.0.0 Beta 1!
It has some bugs, but it supports English so please try it!

Release page: https://github.com/mncrp/monot/releases/tag/build11
