### ISSUE TITLE
[Bug] 「その他」から行けるドキュメントのURL切れ

### ISSUE THREAD

**Issue by kinoko2k** [mncrp/monot#16]
mncrp.github.io/document/monot/
なのでないです。

**Comment by Mf-3d** [comment]
「その他」とはREADMEにある「その他のショートカットキーはこちら」のことでしょうか？
![image](https://github.com/mncrp/monot/assets/84224913/4f23f575-984d-448e-a2e5-21743293c7b8)

**Comment by kinoko2k** [comment]
Monot内のメニューに有るその他です。

**Comment by HidemaruOwO** [comment]
ご報告ありがとうございました
