### ISSUE TITLE
Monot Beta 6でbodyのbackgroundの色が指定されていないページを開いたときに不具合

### ISSUE THREAD

**Issue by Mf-3d** [mncrp/monot#3]
## 問題
タブを切り替えるとこうなりますね。
![image](https://user-images.githubusercontent.com/84224913/150629268-7c31576a-9d14-45da-86fb-c2f940ae02a2.png)
早めに修正ペンで修正することをお勧めします。

**Comment by Sorakime** [comment]
タブ切り替えるだけでそうなるんですか！？

**Comment by waryu-YND** [comment]
再現方法などありましたらお願いします

**Comment by Mf-3d** [comment]
再現は簡単です。
bodyのbackgroundの色が指定されていないページを開きます。
何ということでしょう。
初期化されません。

このバグを再び出すには
最初に何らかのページを開く必要があります。
Monotのホーム画面からbodyのbackgroundの色が指定されていないページにアクセスしても
何も画面が変わらなかったからです。
そして何故かMonotのホームボタンが押せない。

ちなみにbodyのbackgroundの色が指定されていないサイトは
[yyuu51536.github.io/keikentanmatu](yyuu51536.github.io/keikentanmatu)や、
[mf7cli.vercel.app/aa](mf7cli.vercel.app/aa)(Vercelの404ページ)などです。

多分

**Comment by Mf-3d** [comment]
> タブ切り替えるだけでそうなるんですか！？

そうですね。
私が最初に見つけた方法はそれです。

**Comment by Sorakime** [comment]
わかりました。一応BrowserView生成時にbackground: '#ffffff'というオプションを適用させていますが、何故か動いてないみたいです。
ページを移動させたときに毎回setBackgroundColor...を実行することで修正可能です。
また、こちらのバグは正式版では消滅してると思います。少なくともこちら側では修正されたことが確認されています。

**Comment by Mf-3d** [comment]
分かりました。
ありがとうございます。
