### ISSUE TITLE
タブの表示だけが消えない(もしかしたらズレてるのかもしれない)

### ISSUE THREAD

**Issue by Mf-3d** [mncrp/monot#8]
![](https://user-images.githubusercontent.com/84224913/174418276-dcc0025b-78a8-4494-9352-37bfde6a5460.png)

内部のタブは消えてると思うのですがタブの表示が消えていないようです...。

(もしかしたらズレてるかもしれないしコードを見てないから分からない)

**Comment by Mf-3d** [comment]
![](https://user-images.githubusercontent.com/84224913/174418464-d204a0d7-b787-4515-ab18-20887819a466.png)
多分ズレてます...

**Comment by Sorakime** [comment]
ありがとうございます。
「ズレている」だけでは修正が困難なため、再現方法等を教えていただけると幸いです

**Comment by Mf-3d** [comment]
えっとバグを出す方法を忘れてしまったので探しています。

**Comment by Sorakime** [comment]
> えっとバグを出す方法を忘れてしまったので探しています。

待ってまーす

**Comment by Sorakime** [comment]
えっ

**Comment by Mf-3d** [comment]
再現方法を忘れましたねぇ

**Comment by Mf-3d** [comment]
頑張って探してます

**Comment by Sorakime** [comment]
待ってまーす

**Comment by Sorakime** [comment]
1ヶ月も待ってまーす

**Comment by Mf-3d** [comment]
もう忘れたので閉じまーす

**Comment by Sorakime** [comment]
泣きますね、

**Comment by Mf-3d** [comment]
えぇ、、

**Comment by Sorakime** [comment]
泣いてる。涙がボロボロ.....

**Comment by Mf-3d** [comment]
Superfly聴いて落ち着け（？）

**Comment by Sorakime** [comment]
さっきまで聞いてました、、、
そしたら歌詞に感動して涙ボロボロ、、、（？）

**Comment by Mf-3d** [comment]
🤔
